### PR TITLE
Tuya version 3.3

### PR DESCRIPTION
**Pull request by basdelfos**
Revamped deprecated plugin to work with Tuya devices with protocol version 3.3 (fw: 1.0.5).
Currently working and tested devices are Outlet and Dimmer (LightBulb).

Tested with devices:
https://www.aliexpress.com/item/33010332202.html?spm=a2g0s.9042311.0.0.35b14c4dlBYb5M

https://www.aliexpress.com/item/32957842763.html?spm=a2g0s.9042311.0.0.35b14c4dlBYb5M

### CODE REVIEW

**Comment by codetheweb** [comment]
Thanks for taking the time to work on this @basdelfos.

A few things:
- Do you know if this is backwards compatible with older devices?
- Please update the README to include instructions for specifying the firmware.
- Please revert the README to the current deprecated message, unless you want to become the lead maintainer (which I'm happy for you to do) :).

**Comment by basdelfos** [comment]
> Do you know if this is backwards compatible with older devices?

I'm not sure as I don't own devices with an older fw / protocol. But making a judgement about the changes I made, I don't suspect that there is an issue with devices with an older fw / protocol version as the user have to specify the version in the config specific with the devices that have protocol version 3.3.

> Please update the README to include instructions for specifying the firmware.

Will do.

> Please revert the README to the current deprecated message, unless you want to become the lead maintainer (which I'm happy for you to do) :).

Well, I thought about this. While the other plugin doesn't work with devices having protocol 3.3 and I need to maintain this code to have my devices it to work with upcomming Homebridge or TuyApi changes, maybe that's a good idea. The last few days I worked through all lines of code and I now have a good understanding how the code is setup and how it works. I only own Tuya smart plugs (outlet) and dimmers (lightbulb), and therefor only can test with those devices.
What do I need to do to become the lead maintainer for this plugin?

**Comment by codetheweb** [comment]
Thank you for making those changes.

If you're still on board with becoming the main maintainer, I'll transfer ownership of the published package and this repository to you.

**Comment by codetheweb** [comment]
Hey @basdelfos you still interested?

**Comment by basdelfos** [comment]
@codetheweb. The last week and a half I put in a lot of late hours into this plugin, but I can't not seem to get the connection stable enough. Randomly devices will lose connection and generate errors in the plugin. I managed to prevent that Homebridge crashes due to the connection errors but, trying to reconnect after a dropped connection wasn't stable enough. I needed to restart Homebridge a few times a day to get the connection running again. It isn't the quality of my WIFI netwerk, because I have several AP's around the house and very corner of the house I have blazing fast WIFI.

Before I started using Homebridge I tested Home Assistant for a few weeks. Home Assistant does have a very stable Tuya plugin, so I dug into how Home Assistant controls Tuya devices. Apparently Tuya has a special Web API made by Tuya to control Tuya devices from Home Assistant. Last week I spend a few hours in examining the protocol and managed to control the Tuya devices with Postman. After that I spend one evening in making a new Homebridge plugin that uses this Web API.  Performance and latency is very high, the plugin is very lightweight. Only downside is that it uses cloud polling to get device state updates instead of near real-time updates over UDP. On the other side, if a user only controles Tuya devices with Homebridge, the state will always be up to date. I also integrated state caching so that the response is really fast. The cache is updated every 10 seconds by default. The API only needs one API call to get the state of all devices.

You can take a look at the plugin here: https://github.com/basdelfos/homebridge-tuya-web

For now the dimmer and outlet devices are implemented and working very stable, I didn't need to restart Homebridge since I start using the new plugin.

I know there is also a Tuya Cloud API which can be used. I took at that too, but from user perspective that one is much more complex to setup. The user has to go to the Tuya website and make a developer account to generate keys to get access to the API. Downside also is that this API only seems to work if the devices are registered in the Tuya App. I use the Smart Life App and my devices don't show up in the Tuya Cloud API. 

The Web API that I now use can control devices that are registered with Tuya App and Smart Life App (even some more whitelabel branded Apps).

So, answer to your question seems straight forward. As I now created this new plugin that seems to be more stable (for me atleast) I rather spend my time and energie in extending and developing this plugin. I need to implement a few other device types that are also supported by this Web API.

**Comment by codetheweb** [comment]
It's strange that your connection using this plugin has been spotty, it's always been extremely stable for me...

But good work creating the new plugin; I'll update the README to direct users to it.  Your method also makes it easier for the average user to add Homebridge support to their Tuya products since they don't have to extract their localKey, which is a nice bonus. :)

**Pull request merged**
