### PR TITLE
Adds Support for Basic Dimmer Switch

### PR DESCRIPTION
**Pull request by GioCirque**
Added optional ability to use a tuya based dimmer switch, not a color bulb, just the dimmer. Tested with six simultaneous [MJ-SD01](https://smile.amazon.com/gp/product/B07FXYSVR1) controlling LED lights via Homebridge on HomePod, Apple Watch, and iPhone. Works as expected with scenes and triggers.

### CODE REVIEW

**Comment by NorthernMan54** [comment]
This looks very nice, just looking at the code did you implement the new event based model?

**Comment by NorthernMan54** [comment]
If Max thinks this looks good, I was thinking of adding my event driven code to it.  I have a separate branch of this where I built an event driven model, but I used a different approach for multiple device types which wasn’t in alignment with Max’s direction.  And needed to refactor it immensely prior to taking it in.  So am thinking using your code as a base makes sense.

PS - I also have dimmer switches, and am really interested in this feature as I want HomeKit to reflect the local status.

**Comment by codetheweb** [comment]
@GioCirque thanks for all the great work.  I'll look at this in more detail tonight, but looks like there's just a few changes to make and then it's good to go.

@NorthernMan54 what do you mean about multiple device types?  I don't think we've discussed this before (other than the product key thing).

**Comment by NorthernMan54** [comment]
@codetheweb I tested this with my wifi dimmer and it works great.  I'm thinking you should be able to publish this.

In regards to multiple device types I was referring to my productkey thing.

@GioCirque Worked really great for myself, well done

**Comment by codetheweb** [comment]
@NorthernMan54 thanks for testing.  @GioCirque: again, thanks for all the work you put into this.  Merging and publishing now.

**Comment by NorthernMan54** [comment]
@GioCirque Ooops when testing with mine, I found that the brightness is not controllable.  For mine the device object looks like this

TuyAPI Data: 192.168.1.190 { devId: '07200106bcddc2ef159d', dps: { '1': true, '3': 255 } } 10 +0ms

And the plugin is sending this

TuyAPI   dps: { '2': 114 } } +0ms

When attempting to change the brightness

**Comment by GioCirque** [comment]
@NorthernMan54 Glad to hear it! I’m enjoying the heck out of it. Thanks for doing the leg work on the GenericAccessory!!

**Comment by codetheweb** [comment]
Well, guess I'll hold off on publishing it.

**Comment by NorthernMan54** [comment]
@codetheweb I think you should publish it as it, but see what other feedback is received

**Comment by NorthernMan54** [comment]
publish as is and see what other feedback is received

**Comment by codetheweb** [comment]
@GioCirque maybe you could add a `dps` option like in the `generic` accessory for brightness with the default set to `2`?

**Comment by codetheweb** [comment]
I'll publish it now, but if you want to make a second PR with those changes it'd be great.

**Comment by GioCirque** [comment]
It’s already there on line 17 of dimmer.js

this.dpsMap = {
      onOff: deviceConfig.dpsOn || 1,
      brightness: deviceConfig.dpsBright || 2,
    };

**Comment by codetheweb** [comment]
Oh ok, great.  I'll update the README then.

**Comment by GioCirque** [comment]
Sorry, I forgot to document that. The min and max for the brightness are also in there.

**Comment by NorthernMan54** [comment]
Testing again, give me 15

**Comment by GioCirque** [comment]
@NorthernMan54 Can you point me to the event based work you mentioned? I’d like to check that out.

**Comment by NorthernMan54** [comment]
@codetheweb Just completed testing, and that worked....my config.json looks like this for my ceSmart Wifi Dimmer Switch

```
 "platforms": [{
    "platform": "TuyaPlatform",
    "name": "TuyaPlatform",
    "devices": [{
      "name": "Test Device 1",
      "id": "XXXXXXXXX",
      "key": "XXXXXXXX",
      "type": "dimmer",
      "dpsBright": 3
    }]
  }]
```

@GioCirque Take a look here in about an hour, I'm in the middle of updating your code base to be event based.

https://github.com/NorthernMan54/homebridge-tuya/tree/Dimmer

**Comment by NorthernMan54** [comment]
@GioCirque @codetheweb Pull request #18 adds events to the dimmer

**Pull request merged**
