### PR TITLE
Dimmer with events

### PR DESCRIPTION
**Pull request by NorthernMan54**

### CODE REVIEW

**Comment by GioCirque** [comment]
@NothernMan54 Can you change the hard-codes value sent for brightness to use the min/max range from options from deviceConfig? My devices freak out if that value is set lower than 11.

**Comment by NorthernMan54** [comment]
@GioCirque I was looking at my commit, and it is included.  Are you thinking of something else?

https://github.com/codetheweb/homebridge-tuya/pull/18/files#diff-75f6c91a049938dfc57cb00d7181b04aR29

**Comment by GioCirque** [comment]
@NorthernMan54 Look at line #54. I changed it, when I included your changes, to be the reverse of the calculation in the set handler.

https://github.com/codetheweb/homebridge-tuya/pull/20/files#diff-75f6c91a049938dfc57cb00d7181b04a

**Comment by NorthernMan54** [comment]
Closing

**Pull request closed without merging**
